const db = require("./app/models");

const modelsData = [
    // Add all 33 models + ROXIE SINNER
    {
        id: "roxie_sinner_001",
        name: "ROXIE SINNER",
        profile: "Model Name: Roxie Sinner\nImportant Info: 1. Video calls (SnapChat) - Please ask your TL for the link\n2. no Arab name calling\n3. No hijab scenes\n4.No religious related sexting or content \n5. CUSTOMS TURNAROUND: Try to do them in 4-5 days\n6. .\n7. can do masturbation during video calls\n8. Agency to book her for pro-porn shooting\n9. CAN DO BG custom but no lower than 600 \n10. DO NOT MENTION ANYTHING RELATED TO ESCORTS OR IRL BOOKINGS\n11. CAN FOLLOW \\ ADD FAN BACK ( IG , SNAP)\nBUT WILL NEVER MESSAGE. PRICE STARTS AT 40+\n12. CANT DO ANAL - EVEN BUTT PLUg\n13. Roxie has 6 tattoos\n14. No Horse Dildo\n15. When closing VC please note 2 mins is the minimum. \n16.  If anyone asks if she's Muslim, don't answer with “I'm Syrian”, they're asking about her religion, not her nationality. Instead, say she's not Muslim and does not participate in any religion.\n17- if fans want to speak in arabic, say english please and explain she doesn't have an arabic keyboard and left syria when she was young so english is easier \n🔸 Texting Style	\n🔸 Chatting Guidelines	\n🌟 VIP Page/GF Exp	\"VIP Club: \nGirlfriend Experience: \"\n👥 Regular Customers	\n🎂 Age	24 years old | 20/12/2000 \n📏 Height	5”7\n🌍 Ethnicity	Arabic\n🏡 Hometown	Syria\n📍 Location	Las Vegas , USA\n🕒 Last Updated	July 1, 2024\n💼 Profession	\"I shoot pro porn & I take private bookings with fans.\nPhotography career possible as well & the fans know I shoot film photography \"\n🎭 Model Niche	No niche just the Arab gf you've always wished for🤣\n😄 Personality	\"Calls fans - Babe, boo, bby, baby\n\nTo laugh - Lmfao, lol or 🤣🤣\"\n🐾 Pets	\"Animal:  2 cats\nBreed: N/A\nNames: Smoke and Leo\n\nAdditional information: Smoke: Smokey colored w white stripes about 12pounds adopted in 2020 sleeps by the TV.\nLeo: mini tiger about 14 pounds adopted also in 2020 about 4 months after smoke & he sleeps in my arms w his back holding up my face as a pillow lol\"\n🧸 Hobbies	Smoking, making jewelry, photography & picnics/nature activities \n💬 Languages Spoken	English  and Arabic\n📺 Favourite Media	\"🎵 Music:  Rap/hip hop, old 60's & 70's music, r&b, Arabic music & indie\n\n📺 TV/Film: Barely watch tv😭 but if I do it's something comedy, horror or action \"\n🧍 Body Sizes	\"👠 Shoe Size: 9\n\n👙 Bra Size: 34 DD\n\nWaist: 41 inches\"\n🧷 Body Modifications	All natural\n📲 Socials	\"https://www.theroxiesinner.com/\n\nhttps://www.instagram.com/_roxiesinner_/?hl=en\n\nhttps://www.instagram.com/roxiesinneragain/\"\n❤️ Relationship Status	👱🏻‍♀️ Single  \n📌 General Info	Friendly, cute, nice, dirty\n🎲 Misc Facts	\"I'm very friendly & nice to fans both online & in person when I meet them at conventions! So pls translate that well into text!\nAlso fans know I'm pro Palestine & sometimes they'll text about it or praise me for it & shit just so yk\"",
        pricing: "PRICE LIST - LAST UPDATED: 08/12/2024\nClient: Roxie Sinner\nSummary:\n\"1. Video calls via OF 1-1 live \n2. no Arab name calling\n3. No hijab scenes\n4.No religious related sexting or content \n5. CUSTOMS TURNAROUND: Try to do them in 4-5 days\n7. can do masturbation during video calls\n8. Agency to book her for pro-porn shooting 9 . CAN DO BG CONTENT but NO LOWER THAN 600 \n09. CAN FOLLOW \\ ADD FAN BACK ( IG )\nBUT WILL NEVER MESSAGE. PRICE STARTS AT 40+\nWhen closing VC please note 2 mins is the minimum. \"\n\n\n\nFully clothed boob/booty pics	$5+\nBooty pics in panties/boob pics in bra	$5+\nDick rating text	$5+\nNaked boob/ass pictures	$7+\nPussy pictures	$10+\nDick rating speech with persons name	$15+\nTopless dick rating	$40+\nMasturbation videos	$15+\nB/G Blowjob Videos	$25+\nSex Scenes 	$30+\nSigned Polaroid	$50+\nCustom Pictures (Clothing & No Face)	$10+\nCustom Pictures (Clothing & Face)	$15+\nCustom Pictures (Naked & No Face)	$25+\nCustom Pictures (Naked & Face)	$30+\n\"Custom videos (fully clothed/lingerie)\n2 minutes minimum duration\"	$15 per min\n\"Custom videos (Naked)\n2 minutes minimum duration \"	$100 per min\nVIDEO CALLS ( 3mins minimum) 	$50 per min (maybe well lower it if needed)\nJoi videos	$30+\nUsed Panties 	$100+\nUsed Lingerie	$150+\nTHESE ARE MINIMUM PRICES FEEL FREE TO CHARGE MORE IF YOU CAN, BUT DON'T GO BELOW THESE UNLESS APPROVED BY MANAGEMENT!",
        dosAndDonts: "DOS AND DON'TS - LAST UPDATED: 01/07/2024\nClient: Roxie Sinner\nContent Type	Yes/No\nFully Nude 	TRUE\nShows Face in Explicit Content	TRUE\nDirty Talk in Videos	TRUE\nFinger sucking 	TRUE\nSigned Polaroids	TRUE\nVideo Calls 	TRUE\nText Dick Rates 	TRUE\nVoice Dick Rates 	TRUE\nVideo Dick Rates with face 	TRUE\nSmall Penis Humiliation 	TRUE\nFemdom Voice notes 	TRUE\nFemdom Videos 	FALSE\nStrapon Content 	TRUE\nNon-explicit videos with Face 	TRUE\nExplicit videos with Face 	TRUE\nJOI (jerk off instructions) Audio	TRUE\nJOI (jerk off instructions) Video	TRUE\nCustom Videos 	TRUE\nCustom Videos Longer than 5 mins	TRUE\nGirl/Girl Content 	TRUE\nBoy/Girl Content 	TRUE\nBlow Job Content	TRUE\nSelling Underwear/Lingerie	TRUE\nDildo Sucking Videos 	TRUE\nDildo Masturbation Videos 	TRUE\nPussy Pictures 	TRUE\nSquirting Content	TRUE\nFingering Pussy Videos 	TRUE\nNaked Ass Pictures	TRUE\nNaked Shower Videos	TRUE\nTwerking Videos 	TRUE\nAnal masturbation	FALSE\nAnal sex video	FALSE\nDeepthroat content	TRUE\nNipple pinching content	FALSE\nFetish self spanking	TRUE\nFetish blindfold and self binding	FALSE",
        extraTabs: []
    }
    // Add other 33 models here in the same format...
];

db.mongoose.connect(db.url)
  .then(() => {
    const Model = db.models;
    Model.insertMany(modelsData)
      .then(() => {
        console.log("Models seeded!");
        process.exit(0);
      })
      .catch(err => console.log(err));
  })
  .catch(err => console.log(err));